version: '3.8'

networks:
  mygridnetwork:
    driver: bridge

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"   # Event bus publish
      - "4443:4443"   # Event bus subscribe
      - "4444:4444"   # Grid UI and Hub
    networks:
      - mygridnetwork

  chrome-node:
    image: selenium/node-chrome
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - mygridnetwork

  firefox-node:
    image: selenium/node-firefox
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - mygridnetwork
